name: Pruebas

on:
  pull_request:
    branches: [develop,staging, main]
  push:
    branches: [develop]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
      - run: pip install -r requirements.txt
      - name: Correr pruebas
        env:
          DATABASE_URL: postgresql://falso:falso@localhost/falso
          SECRET_KEY: clave-solo-para-pruebas
        run: pytest